In [ ]:
import tensorflow as tf
from tensorflow.keras import layers, models

# Load dataset (e.g., MNIST)
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

# Build the model
model = models.Sequential([
    layers.Flatten(input_shape=(28, 28)),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.2),
    layers.Dense(10)
])

# Compile the model
model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

# Train the model
model.fit(x_train, y_train, epochs=5)

# Evaluate the model
model.evaluate(x_test, y_test, verbose=2)


11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


/usr/local/lib/python3.10/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - accuracy: 0.8607 - loss: 0.4732
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9552 - loss: 0.1518
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9671 - loss: 0.1076
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9739 - loss: 0.0867
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9765 - loss: 0.0765
313/313 - 1s - 2ms/step - accuracy: 0.9768 - loss: 0.0747


[0.07471597194671631, 0.9768000245094299]

Keras offers three main ways to build neural networks: Sequential, Functional, and Subclassing API. Each method has its own advantages and use cases.

1. Sequential API
The Sequential API is the simplest way to build a model in Keras. It allows you to create models layer-by-layer for most problems.

When to Use


When building simple, feedforward neural networks.
When the model has a single input and a single output.
When layers are stacked sequentially.


Advantages


Easy to use and understand.
Minimal code for straightforward models.


Limitations


Not flexible for models with multiple inputs or outputs.
Not suitable for complex models with shared layers or non-linear data flows.

In [ ]:
from keras.models import Sequential
from keras.layers import Dense

# Define the input dimension
input_dim = 784  # Example for MNIST, adjust as needed

num_classes = 10 # Example for MNIST, adjust as needed

model = Sequential([
    Dense(64, activation='relu', input_shape=(input_dim,)),
    Dense(64, activation='relu'),
    Dense(num_classes, activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

2. Functional API
The Functional API is more flexible than the Sequential API. It allows you to build complex models, such as multi-input/output models, shared layers, and models with residual connections.

When to Use

When building models with multiple inputs and outputs.
When you need to share layers across different parts of the model.
When building non-linear models, such as residual networks or models with branches.

Advantages


Greater flexibility.
More control over the model architecture.
Suitable for complex models.


Limitations

Slightly more complex syntax compared to the Sequential API.


In [ ]:
from keras.layers import Input, Dense
from keras.models import Model

# Define the input dimension
input_dim = 784  # Example for MNIST, adjust as needed
num_classes = 10 # Example for MNIST, adjust as needed

inputs = Input(shape=(input_dim,))
x = Dense(64, activation='relu')(inputs)
x = Dense(64, activation='relu')(x)
outputs = Dense(num_classes, activation='softmax')(x)

model = Model(inputs=inputs, outputs=outputs)

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

3.Subclassing API

The Subclassing API gives you complete control by allowing you to subclass the Model class. This approach is the most flexible but requires more code and a deeper understanding of Keras.

When to Use

When you need complete flexibility and control over your model.
When implementing custom layers or complex models that don’t fit into the Sequential or Functional API.

Advantages

Maximum flexibility.
Allows for creating highly customized models and layers.
Best for research and experimentation with novel architectures.

Limitations

Requires more boilerplate code.
Can be more difficult to debug.
Requires a deeper understanding of Keras and TensorFlow.


In [ ]:
from keras import Model
from keras.layers import Dense
import tensorflow as tf

# ... [Your existing MyModel class definition] ...

model = MyModel()

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Load or generate your training and validation data here
# Example using placeholder data:
import numpy as np
x_train = np.random.rand(100, 784)  # Replace with your actual training data
y_train = np.random.rand(100, num_classes) # Replace with your actual training labels
x_val = np.random.rand(20, 784)  # Replace with your actual validation data
y_val = np.random.rand(20, num_classes) # Replace with your actual validation labels

# Example usage with data
model.fit(x_train, y_train, epochs=10, batch_size=32, validation_data=(x_val, y_val))

Epoch 1/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 82ms/step - accuracy: 0.1199 - loss: 12.0143 - val_accuracy: 0.1000 - val_loss: 12.8091
Epoch 2/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.0952 - loss: 13.0007 - val_accuracy: 0.1000 - val_loss: 14.9754
Epoch 3/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.0931 - loss: 15.3126 - val_accuracy: 0.1000 - val_loss: 16.6188
Epoch 4/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.1140 - loss: 16.9284 - val_accuracy: 0.1000 - val_loss: 18.0025
Epoch 5/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.1046 - loss: 18.3785 - val_accuracy: 0.1000 - val_loss: 19.2481
Epoch 6/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.1046 - loss: 19.7657 - val_accuracy: 0.1000 - val_loss: 21.9065
Epoch 7/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.1140 - loss: 22.7802 - val_accuracy: 0.1000 - val_loss: 25.3751
Epoch 8/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.0798 - loss: 25.9427 - val_accuracy: 0.0500 - va

Summary

Sequential API: Best for simple, linear stack of layers. Easy to use and understand.

Functional API: Best for complex models with multiple inputs/outputs, shared layers, and non-linear architectures. Offers greater flexibility.

Subclassing API: Best for highly customized and complex models. Provides maximum flexibility but requires more code and deeper understanding.

Choose the API based on the complexity and requirements of your neural network architecture.

In [ ]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.17.0


Load a dataset

Load and prepare the MNIST dataset. The pixel values of the images range from 0 through 255. Scale these values to a range of 0 to 1 by dividing the values by 255.0. This also converts the sample data from integers to floating-point numbers:

In [ ]:
from keras.layers import Dense
from keras.models import Sequential

model = Sequential([
    Dense(64, activation='relu', input_shape=(input_dim,)),
    Dense(64, activation='relu'),
    Dense(num_classes, activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])


NameError: name 'input_dim' is not defined

In [ ]:
from keras.layers import Dense
from keras.models import Sequential

model = Sequential([
    Dense(64, activation='relu', input_shape=(input_dim,)),
    Dense(64, activation='relu'),
    Dense(num_classes, activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])


In [ ]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


Build a machine learning model


Build a tf.keras.Sequential model:

In [ ]:

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Sequential is useful for stacking layers where each layer has one input tensor and one output tensor. Layers are functions with a known mathematical structure that can be reused and have trainable variables. Most TensorFlow models are composed of layers. This model uses the Flatten, Dense, and Dropout layers.

For each example, the model returns a vector of logits or log-odds scores, one for each class.

In [ ]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.8549914 , -0.60842115, -0.6975674 ,  0.67272735,  0.61200285,
        -0.41180384, -0.33797556, -0.41248542,  0.5526458 , -0.17192067]],
      dtype=float32)

The tf.nn.softmax function converts these logits to probabilities for each class:

In [ ]:
tf.nn.softmax(predictions).numpy()

array([[0.04300801, 0.05503431, 0.05034053, 0.19816604, 0.1864906 ,
        0.06699206, 0.07212512, 0.06694642, 0.17574318, 0.08515365]],
      dtype=float32)

Define a loss function for training using losses.SparseCategoricalCrossentropy:

The loss function takes a vector of ground truth values and a vector of logits and returns a scalar loss for each example. This loss is equal to the negative log probability of the true class: The loss is zero if the model is sure of the correct class.

This untrained model gives probabilities close to random (1/10 for each class), so the initial loss should be close to -tf.math.log(1/10) ~= 2.3.

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
loss_fn(y_train[:1], predictions).numpy()

2.7031813

Before you start training, configure and compile the model using Keras Model.compile. Set the optimizer class to adam, set the loss to the loss_fn function you defined earlier, and specify a metric to be evaluated for the model by setting the metrics parameter to accuracy.

In [ ]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

Train and evaluate your model
Use the Model.fit method to adjust your model parameters and minimize the loss:

In [ ]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.8573 - loss: 0.4870
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 3ms/step - accuracy: 0.9566 - loss: 0.1501
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9666 - loss: 0.1126
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - accuracy: 0.9727 - loss: 0.0869
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9778 - loss: 0.0730


The Model.evaluate method checks the model's performance, usually on a validation set or test set.

In [ ]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - 2ms/step - accuracy: 0.9767 - loss: 0.0789


[0.07889510691165924, 0.9767000079154968]

The image classifier is now trained to ~98% accuracy on this dataset. To learn more, read the TensorFlow tutorials.

If you want your model to return a probability, you can wrap the trained model, and attach the softmax to it:

In [ ]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [ ]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.70193708e-08, 7.98500016e-11, 1.76239539e-07, 6.40839280e-05,
        6.41173226e-12, 1.11787315e-07, 5.63594581e-14, 9.99933600e-01,
        7.93375587e-09, 1.93560822e-06],
       [2.87408568e-08, 1.53344532e-04, 9.99834299e-01, 8.08868026e-06,
        1.38212616e-13, 7.26504652e-07, 1.10848788e-08, 1.26955426e-13,
        3.44109685e-06, 2.13663332e-12],
       [1.49803000e-07, 9.99346673e-01, 1.52537059e-05, 1.02430031e-05,
        2.42145237e-04, 1.09026842e-05, 7.57819953e-06, 1.18828342e-04,
        2.45909934e-04, 2.30183468e-06],
       [9.99886036e-01, 3.00490726e-08, 1.01013120e-05, 2.42062512e-08,
        9.93535423e-07, 1.48428626e-06, 9.51742259e-05, 2.13178009e-06,
        1.48029118e-08, 4.01359694e-06],
       [1.07154392e-06, 1.08242526e-09, 1.79727740e-05, 4.79124481e-07,
        9.98365223e-01, 3.88009056e-07, 1.87868045e-06, 4.32323850e-06,
        1.02492390e-06, 1.60753995e-03]], dtype=float32)>